/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_blobsnode_free: (a: number, b: number) => void;
export const blobsnode_complete_size: (a: number, b: number, c: number) => any;
export const blobsnode_download: (a: number, b: number, c: number) => any;
export const blobsnode_endpoint_id: (a: number) => [number, number];
export const blobsnode_get: (a: number, b: number, c: number) => any;
export const blobsnode_import: (a: number, b: any) => any;
export const blobsnode_spawn: () => any;
export const start: () => void;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingsource_cancel: (a: number) => void;
export const intounderlyingsource_pull: (a: number, b: any) => any;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const intounderlyingsink_abort: (a: number, b: any) => any;
export const intounderlyingsink_close: (a: number) => any;
export const intounderlyingsink_write: (a: number, b: any) => any;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const intounderlyingbytesource_pull: (a: number, b: any) => any;
export const intounderlyingbytesource_start: (a: number, b: any) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const ring_core_0_17_14__bn_mul_mont: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const wasm_bindgen__closure__destroy__hd3a9bb98e0b50058: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__he9a7a811b172d63e: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__ha071cb228bf0a101: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h4fc4d32b8bf38386: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__hefbc5bc76a0388bc: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h788e1e5e966a3471: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h6c48c2f11434e0ba: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h7144c514e40f03d0: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h4bbee9be6a9bf555: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hecf30ba54fa53b31: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1dae589765e137be: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h63e45b1af0ed2e4a: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h7fb2534e8b479b80: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
