/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_blobsnode_free: (a: number, b: number) => void;
export const blobsnode_complete_size: (a: number, b: number, c: number) => any;
export const blobsnode_download: (a: number, b: number, c: number) => any;
export const blobsnode_endpoint_id: (a: number) => [number, number];
export const blobsnode_get: (a: number, b: number, c: number) => any;
export const blobsnode_import: (a: number, b: any) => any;
export const blobsnode_spawn: () => any;
export const start: () => void;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const intounderlyingsink_abort: (a: number, b: any) => any;
export const intounderlyingsink_close: (a: number) => any;
export const intounderlyingsink_write: (a: number, b: any) => any;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingsource_cancel: (a: number) => void;
export const intounderlyingsource_pull: (a: number, b: any) => any;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const intounderlyingbytesource_pull: (a: number, b: any) => any;
export const intounderlyingbytesource_start: (a: number, b: any) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const ring_core_0_17_14__bn_mul_mont: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const wasm_bindgen__closure__destroy__he1b35a6c06e1ddb3: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h12408e4d2144c895: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__he4e46a15b3b6da87: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__heac77dc8d198a3db: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__he06c6f45a38a54fa: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h58efaf5197e5de3a: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h6b1b8bbfee0d3e92: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h441bee516e9b07d4: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h34fbdd8836dfeb85: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h31471e852fb6c802: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hbf41809ff1ccb2fa: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__haa0573f6386476f2: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h821900d8264368d6: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
