/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_blobsnode_free: (a: number, b: number) => void;
export const blobsnode_complete_size: (a: number, b: number, c: number) => any;
export const blobsnode_download: (a: number, b: number, c: number) => any;
export const blobsnode_endpoint_id: (a: number) => [number, number];
export const blobsnode_get: (a: number, b: number, c: number) => any;
export const blobsnode_import: (a: number, b: any) => any;
export const blobsnode_spawn: () => any;
export const start: () => void;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingsource_cancel: (a: number) => void;
export const intounderlyingsource_pull: (a: number, b: any) => any;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const intounderlyingsink_abort: (a: number, b: any) => any;
export const intounderlyingsink_close: (a: number) => any;
export const intounderlyingsink_write: (a: number, b: any) => any;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const intounderlyingbytesource_pull: (a: number, b: any) => any;
export const intounderlyingbytesource_start: (a: number, b: any) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const ring_core_0_17_14__bn_mul_mont: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const wasm_bindgen__closure__destroy__h1b449bd8e350af95: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h07c9d9a00ee05c90: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__hf0e68b9f1a9e1fe8: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h9044571d61c1b3e8: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h122ce4c39af727de: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h12e8ab036b4be1e9: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h738eab8d00135c20: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h15f3c45775f37e0d: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h35206f2c4bfdc438: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hebd4f37d08ede1db: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h839cf75c62217a1a: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hb59de10f871839ef: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h38475aa04c8d91fd: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
