/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_blobsnode_free: (a: number, b: number) => void;
export const blobsnode_complete_size: (a: number, b: number, c: number) => any;
export const blobsnode_download: (a: number, b: number, c: number) => any;
export const blobsnode_endpoint_id: (a: number) => [number, number];
export const blobsnode_get: (a: number, b: number, c: number) => any;
export const blobsnode_import: (a: number, b: any) => any;
export const blobsnode_spawn: () => any;
export const start: () => void;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingsource_cancel: (a: number) => void;
export const intounderlyingsource_pull: (a: number, b: any) => any;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const intounderlyingsink_abort: (a: number, b: any) => any;
export const intounderlyingsink_close: (a: number) => any;
export const intounderlyingsink_write: (a: number, b: any) => any;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const intounderlyingbytesource_pull: (a: number, b: any) => any;
export const intounderlyingbytesource_start: (a: number, b: any) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const ring_core_0_17_14__bn_mul_mont: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const wasm_bindgen__convert__closures_____invoke__haaff06e475b53765: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h66802ea1906d163f: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__ha5cf909579bf974e: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h5933ab5e112be499: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h90e00b75ae484e25: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h260e509c922efc08: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hafa0f25f31e4df2d: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__he59821b9aa15ea99: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
