/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_blobsnode_free: (a: number, b: number) => void;
export const blobsnode_complete_size: (a: number, b: number, c: number) => any;
export const blobsnode_download: (a: number, b: number, c: number) => any;
export const blobsnode_endpoint_id: (a: number) => [number, number];
export const blobsnode_get: (a: number, b: number, c: number) => any;
export const blobsnode_import: (a: number, b: any) => any;
export const blobsnode_spawn: () => any;
export const start: () => void;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingsource_cancel: (a: number) => void;
export const intounderlyingsource_pull: (a: number, b: any) => any;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const intounderlyingbytesource_pull: (a: number, b: any) => any;
export const intounderlyingbytesource_start: (a: number, b: any) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const intounderlyingsink_abort: (a: number, b: any) => any;
export const intounderlyingsink_close: (a: number) => any;
export const intounderlyingsink_write: (a: number, b: any) => any;
export const ring_core_0_17_14__bn_mul_mont: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h515622588655e8ac: (a: number, b: number, c: any) => void;
export const wasm_bindgen__closure__destroy__hd2ce859e74370ac9: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h84e77fe59aff539f: (a: number, b: number, c: any) => void;
export const wasm_bindgen__closure__destroy__h602cb35f0402a19c: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hfc68c92a2f1e90e7: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__hd4c2439e15638195: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h354babe9fa2a5540: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__hcc814b107b496071: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h7d839b67dd20f7c9: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h0d2796f6747c0223: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h7134ad860473df55: (a: number, b: number, c: any) => void;
export const wasm_bindgen__closure__destroy__h47c4304c7f5d4704: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h400498881dd64829: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
