//
//  ModelData.swift
//  iroh
//
//  Created by Brendan O'Brien on 7/4/23.
//

import Foundation


var networks: [Network] = load("Networks.json")

func load<T: Decodable>(_ filename: String) -> T {
    let data: Data

    guard let file = Bundle.main.url(forResource: filename, withExtension: nil)
    else {
        fatalError("Couldn't find \(filename) in main bundle.")
    }

    do {
        data = try Data(contentsOf: file)
    } catch {
        fatalError("Couldn't load \(filename) from main bundle:\n\(error)")
    }

    do {
        let decoder = JSONDecoder()
        return try decoder.decode(T.self, from: data)
    } catch {
        fatalError("Couldn't parse \(filename) as \(T.self):\n\(error)")
    }
}

//var mockDocEvents: [DocEvent] = load("DocEvents.json")

var anchorEvents = [
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouDeletedKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
]

var mockDocEvents: [DocEvent] = [
    DocEvent(tipe: .DocumentCreated, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerJoined, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerJoined, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerJoined, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerJoined, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerJoined, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerLeft, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerDeletedKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerDeletedKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .Error, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerJoined, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .DocumentCreated, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerJoined, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerJoined, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerJoined, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerJoined, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerJoined, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerLeft, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerDeletedKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .Error, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerJoined, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .DocumentCreated, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerJoined, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerJoined, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerJoined, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerJoined, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerJoined, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerLeft, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerDeletedKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .Error, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerJoined, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .DocumentCreated, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerJoined, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerJoined, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerJoined, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerJoined, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerJoined, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerLeft, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .YouSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerDeletedKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .Error, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerJoined, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
    DocEvent(tipe: .PeerSetKey, ts: Date(), author_id: "Qmfoo...", author_name: "dig", key: "/foo/bar/baz", value: "stuff", message: "oh hai"),
]
