/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_blobsnode_free: (a: number, b: number) => void;
export const blobsnode_complete_size: (a: number, b: number, c: number) => any;
export const blobsnode_download: (a: number, b: number, c: number) => any;
export const blobsnode_endpoint_id: (a: number) => [number, number];
export const blobsnode_get: (a: number, b: number, c: number) => any;
export const blobsnode_import: (a: number, b: any) => any;
export const blobsnode_spawn: () => any;
export const start: () => void;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingsource_cancel: (a: number) => void;
export const intounderlyingsource_pull: (a: number, b: any) => any;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const intounderlyingbytesource_pull: (a: number, b: any) => any;
export const intounderlyingbytesource_start: (a: number, b: any) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const intounderlyingsink_abort: (a: number, b: any) => any;
export const intounderlyingsink_close: (a: number) => any;
export const intounderlyingsink_write: (a: number, b: any) => any;
export const ring_core_0_17_14__bn_mul_mont: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hc495dae91deabd04: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h5b9bc9fc71f2f8b7: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h181d1b40c232baa6: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__haa4c70d68e965eb5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h25a7de72233485d4: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h78a8b36b23579e43: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h916ef38db9a91604: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hd086356b2a1a0026: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h1c570e0d846d2f4d: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
