[package]
edition = "2021"
name = "whoami"
version = "0.1.0"

[dependencies]
anyhow = "1.0.98"
axum = "0.8.4"
bytes = "1.10.1"
ciborium = "0.2.2"
iroh = "0.35.0"
iroh-gossip = "0.35.0"
iroh-gossip-discovery = "0.2.0"
serde = "1.0.219"
tokio = { version = "1.45.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
